# Generated by Django 3.1.7 on 2021-03-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuore', '0004_auto_20210329_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeinvoice',
            name='invoicing_data',
        ),
        migrations.AddField(
            model_name='activeinvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuore.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeinvoice',
            name='issuer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cuore.invoicingdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activeinvoice',
            name='name',
            field=models.CharField(help_text='Offer name', max_length=255),
        ),
    ]
